<footer>
	<nav>
		<div>
		    <a href="https://nnuriilengir.github.io/">Home Page</a>
            <a href="https://nnuriilengir.github.io/posts/">Posts</a>
            <a href="https://nnuriilengir.github.io/tutorials/">Tutorials</a>
            <a href="https://nnuriilengir.github.io/news/">News</a>
			 <a href="https://nnuriilengir.github.io/about/">About</a>
		</div>
		<div>
			<a href="http://www.ubuntu-tr.net/">Home Page</a>
			<a href="https://github.com/nnuriilengir">GitHub</a>
			<a href="https://www.facebook.com/profile.php?id=100009844125117">Facebook</a>
			<a href="https://twitter.com/_cilengirnuri">Twitter</a>
			<a href="https://stackoverflow.com/users/8382507/aimlesslight?tab=profile">Stack Overflow</a>
		</div>
	</nav>
    <div class="ayirac"></div>
    <div class="bilgi">
        <p>Tasarım: <a href="https://ubuntu-tr.net/">Ubuntu Türkiye</a> • Alt yapı: <a href="https://jekyllrb.com/">Jekyll</a> • Proje Sayfası: <a href="https://github.com/ubuntu-tr/ubuntu-tr.github.io">Github</a></p>
        <img src="{{ site.themeDir }}/images/cc-by-sa2.png" />
        <p>Bu sitedeki makaleler <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a> lisansı altındadır.</p>
    </div>

</footer>
