<footer>

    <div class="ayirac"></div>
    <div class="bilgi">
        <img src="{{ site.themeDir }}/images/ni.png" />
      
        <p>Tasarım: <a href="https://ubuntu-tr.net/">Ubuntu Türkiye</a> • Alt yapı: <a href="https://jekyllrb.com/">Jekyll</a> • Proje Sayfası: <a href="https://github.com/ubuntu-tr/ubuntu-tr.github.io">Github</a></p>
        <img src="{{ site.themeDir }}/images/cc-by-sa2.png" />
        <p>Bu sitedeki makaleler <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a> lisansı altındadır.</p>
    </div>

</footer>
