<footer>
    <nav>
        <div>
            <a href="https://ubuntu-tr.net/">Anasayfa</a>
            <a href="https://ubuntu-tr.net/bize-katilin/">Bize Katılın!</a>
            <a href="https://ubuntu-tr.net/iletisim/">İletişim</a>
            <a href="https://ubuntu-tr.net/indir/">İndir</a>
            <a href="https://ubuntu-tr.net/ubuntu-hakkinda/">Ubuntu Hakkında</a>
        </div>
        <div>
            <a href="https://forum.ubuntu-tr.net/">Forum</a>
            <a href="https://forum.ubuntu-tr.net/index.php?action=login">Giriş Yap</a>
            <a href="https://forum.ubuntu-tr.net/index.php?board=2.0">Duyurular</a>
            <a href="https://forum.ubuntu-tr.net/index.php?board=142.0">Acemiler için İlk Durak</a>
            <a href="https://forum.ubuntu-tr.net/index.php?topic=12295.0">Türkiye Tayfası</a>
        </div>
        <div>
            <a href="https://sudo.ubuntu-tr.net/">SUDO</a>
            <a href="https://sudo.ubuntu-tr.net/hakkinda">Hakkında</a>
            <a href="https://sudo.ubuntu-tr.net/sendeyaz/">Sen de Yaz</a>
            <a href="https://forum.ubuntu-tr.net/index.php?topic=26354.msg315930#msg315930">Eski Sayılar</a>
            <a href="http://feeds.feedburner.com/ubuntu-tr/sudo">RSS</a>
        </div>
        <div>
            <a href="http://wiki.ubuntu-tr.net/index.php?title=Ana_Sayfa">Wiki</a>
            <a href="http://wiki.ubuntu-tr.net/index.php?title=Ubuntu">Ubuntu Nedir?</a>
            <a href="http://wiki.ubuntu-tr.net/index.php?title=Kurulum">Kurulum</a>
            <a href="https://wiki.ubuntu-tr.net/index.php?title=Ubuntu_başlangıç_kılavuzu">Ubuntu Başlangıç Kılavuzu</a>
            <a href="https://wiki.ubuntu-tr.net/index.php?title=SSS">Sıkça Sorulan Sorular</a>
        </div>
        <div>
            <a href="http://gezegen.ubuntu-tr.net/">Gezegen</a>
            <a href="http://gezegen.ubuntu-tr.net/basliklar">Tüm Başlıklar</a>
            <a href="http://gezegen.ubuntu-tr.net/kunye/">Künye</a>
            <a href="http://gezegen.ubuntu-tr.net/feed">RSS</a>
            <a href="https://forum.ubuntu-tr.net/index.php?topic=17310.0">Gezegen’e Başvur</a>
        </div>
        <div>
            <a href="http://www.ubuntu.com/">Ubuntu</a>
            <a href="http://askubuntu.com/">AskUbuntu</a>
            <a href="http://ubuntuforums.org/">Ubuntu Forums</a>
            <a href="http://www.ubuntu.com/download">Download</a>
            <a href="https://launchpad.net/">Launchpad</a>
        </div>
    </nav>
    <div class="ayirac"></div>
    <div class="bilgi">
        <img src="{{ site.themeDir }}/images/ni.png" />
        <p>SUDO portal <a href="http://www.netinternet.com.tr/">Netinternet</a> desteği ile barındırılmaktadır.</p>
        <p>Tasarım: <a href="https://ubuntu-tr.net/">Ubuntu Türkiye</a> • Alt yapı: <a href="https://jekyllrb.com/">Jekyll</a> • Proje Sayfası: <a href="https://github.com/ubuntu-tr/ubuntu-tr.github.io">Github</a></p>
        <img src="{{ site.themeDir }}/images/cc-by-sa2.png" />
        <p>Bu sitedeki makaleler <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA</a> lisansı altındadır.</p>
    </div>

</footer>
